// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEwPIH9Iv9aX-H9NSj61bMcFvOhbSmyr0',
    appId: '1:1025713985015:web:62fe392ae28aedc30f8af2',
    messagingSenderId: '1025713985015',
    projectId: 'eventflow-ai-779c8',
    authDomain: 'eventflow-ai-779c8.firebaseapp.com',
    storageBucket: 'eventflow-ai-779c8.firebasestorage.app',
    measurementId: 'G-YXX7WLGJB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF1oJCnAfoTGh57CBXQPeS66KxchLXI_g',
    appId: '1:1025713985015:android:2f94f0baffde7e820f8af2',
    messagingSenderId: '1025713985015',
    projectId: 'eventflow-ai-779c8',
    storageBucket: 'eventflow-ai-779c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCMCnLlchn2oj1FT-HZvBLsiMLXx6jC1s',
    appId: '1:1025713985015:ios:6bb6bf99267c35820f8af2',
    messagingSenderId: '1025713985015',
    projectId: 'eventflow-ai-779c8',
    storageBucket: 'eventflow-ai-779c8.firebasestorage.app',
    iosBundleId: 'com.example.eventflowAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCMCnLlchn2oj1FT-HZvBLsiMLXx6jC1s',
    appId: '1:1025713985015:ios:6bb6bf99267c35820f8af2',
    messagingSenderId: '1025713985015',
    projectId: 'eventflow-ai-779c8',
    storageBucket: 'eventflow-ai-779c8.firebasestorage.app',
    iosBundleId: 'com.example.eventflowAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEwPIH9Iv9aX-H9NSj61bMcFvOhbSmyr0',
    appId: '1:1025713985015:web:7717a544676cf11a0f8af2',
    messagingSenderId: '1025713985015',
    projectId: 'eventflow-ai-779c8',
    authDomain: 'eventflow-ai-779c8.firebaseapp.com',
    storageBucket: 'eventflow-ai-779c8.firebasestorage.app',
    measurementId: 'G-0TF1XSHBF0',
  );

}