// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnLABnoHKvcVgeouH2PCa1d3W59XeVhIA',
    appId: '1:994717544235:web:14d66489da772af1945f6e',
    messagingSenderId: '994717544235',
    projectId: 'eventflow-ai-b36a8',
    authDomain: 'eventflow-ai-b36a8.firebaseapp.com',
    storageBucket: 'eventflow-ai-b36a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNK0ghNVXKkkw7pdXw5P8S24R6E62X5Qw',
    appId: '1:994717544235:android:26db00793e9ec323945f6e',
    messagingSenderId: '994717544235',
    projectId: 'eventflow-ai-b36a8',
    storageBucket: 'eventflow-ai-b36a8.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnvrWP0Qxw-msvOE4Qp4sTvg_i3k2u_SE',
    appId: '1:994717544235:ios:c7544b78af5c7886945f6e',
    messagingSenderId: '994717544235',
    projectId: 'eventflow-ai-b36a8',
    storageBucket: 'eventflow-ai-b36a8.firebasestorage.app',
    iosBundleId: 'com.example.eventflowAi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnvrWP0Qxw-msvOE4Qp4sTvg_i3k2u_SE',
    appId: '1:994717544235:ios:c7544b78af5c7886945f6e',
    messagingSenderId: '994717544235',
    projectId: 'eventflow-ai-b36a8',
    storageBucket: 'eventflow-ai-b36a8.firebasestorage.app',
    iosBundleId: 'com.example.eventflowAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnLABnoHKvcVgeouH2PCa1d3W59XeVhIA',
    appId: '1:994717544235:web:597c1583b8e7ac51945f6e',
    messagingSenderId: '994717544235',
    projectId: 'eventflow-ai-b36a8',
    authDomain: 'eventflow-ai-b36a8.firebaseapp.com',
    storageBucket: 'eventflow-ai-b36a8.firebasestorage.app',
  );
}
